image: node:latest

stages:
  - deploy

variables:
  REGISTRY_URL: "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"

deploy:
  stage: deploy
  script:
    - echo "@scope:registry=https:${REGISTRY_URL}" > .npmrc
    - echo "${REGISTRY_URL}:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  only:
    - master
  environment: production
