# This is a docker compose file to demonstrate and test the mastodon-timeline widget
# Run this docker CLI from the root repo directory:
#
# $ docker compose up

version: "3.3"

services:
  lighttpd:
    image: jitesoft/lighttpd
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./css/mastodon-timeline.css:/var/www/css/mastodon-timeline.css
      - ./js/mastodon-timeline.js:/var/www/js/mastodon-timeline.js
      - ./local-timeline.html:/var/www/index.html
      - ./profile-timeline.html:/var/www/profile-timeline.html
      - ./hashtag-timeline.html:/var/www/hashtag-timeline.html
      - ./theme-timeline.html:/var/www/theme-timeline.html
      - ./multiple-timelines.html:/var/www/multiple-timelines.html
    environment:
      - PORT=80
      - SERVER_NAME=mastodon-timeline
      - SERVER_ROOT=/var/www
      - CONFIG_FILE=/etc/lighttpd/lighttpd.conf
      - SKIP_HEALTHCHECK=false
      - MAX_FDS=1024
